"""
Static circuit facts for the F1 Scoreboard plugin.

Data: laps per race, circuit length (km), current lap record.
Records are the FIA official fastest lap per circuit as of early 2026.
Lap records change — update this dict after any record is broken.
"""

from typing import Dict, List, Optional

# Each entry: keywords for matching (lowercase), display name,
# laps, length in km, lap record time string, record holder, year.
_CIRCUITS: List[Dict] = [
    {
        "keywords": ["bahrain", "sakhir"],
        "name": "Bahrain",
        "laps": 57,
        "length_km": 5.412,
        "record_time": "1:31.447",
        "record_driver": "PER",
        "record_year": 2021,
    },
    {
        "keywords": ["jeddah", "saudi", "corniche"],
        "name": "Jeddah",
        "laps": 50,
        "length_km": 6.174,
        "record_time": "1:30.734",
        "record_driver": "LEC",
        "record_year": 2023,
    },
    {
        "keywords": ["albert park", "melbourne", "australia"],
        "name": "Melbourne",
        "laps": 58,
        "length_km": 5.278,
        "record_time": "1:20.235",
        "record_driver": "LEC",
        "record_year": 2022,
    },
    {
        "keywords": ["suzuka", "japan"],
        "name": "Suzuka",
        "laps": 53,
        "length_km": 5.807,
        "record_time": "1:30.983",
        "record_driver": "LEC",
        "record_year": 2023,
    },
    {
        "keywords": ["shanghai", "china"],
        "name": "Shanghai",
        "laps": 56,
        "length_km": 5.451,
        "record_time": "1:32.238",
        "record_driver": "MSC",
        "record_year": 2004,
    },
    {
        "keywords": ["miami", "hard rock"],
        "name": "Miami",
        "laps": 57,
        "length_km": 5.412,
        "record_time": "1:29.708",
        "record_driver": "VER",
        "record_year": 2023,
    },
    {
        "keywords": ["imola", "emilia", "romagna", "dino ferrari"],
        "name": "Imola",
        "laps": 63,
        "length_km": 4.909,
        "record_time": "1:15.484",
        "record_driver": "HAM",
        "record_year": 2020,
    },
    {
        "keywords": ["monaco", "monte carlo"],
        "name": "Monaco",
        "laps": 78,
        "length_km": 3.337,
        "record_time": "1:10.166",
        "record_driver": "HAM",
        "record_year": 2021,
    },
    {
        "keywords": ["barcelona", "spain", "catalunya", "montmelo"],
        "name": "Barcelona",
        "laps": 66,
        "length_km": 4.657,
        "record_time": "1:16.330",
        "record_driver": "VER",
        "record_year": 2023,
    },
    {
        "keywords": ["montreal", "canada", "gilles villeneuve"],
        "name": "Montreal",
        "laps": 70,
        "length_km": 4.361,
        "record_time": "1:13.078",
        "record_driver": "RUB",
        "record_year": 2004,
    },
    {
        "keywords": ["spielberg", "austria", "red bull ring"],
        "name": "Spielberg",
        "laps": 71,
        "length_km": 4.318,
        "record_time": "1:05.619",
        "record_driver": "BOT",
        "record_year": 2020,
    },
    {
        "keywords": ["silverstone", "britain", "british"],
        "name": "Silverstone",
        "laps": 52,
        "length_km": 5.891,
        "record_time": "1:27.097",
        "record_driver": "HAM",
        "record_year": 2020,
    },
    {
        "keywords": ["hungaroring", "hungary", "budapest"],
        "name": "Budapest",
        "laps": 70,
        "length_km": 4.381,
        "record_time": "1:16.627",
        "record_driver": "HAM",
        "record_year": 2020,
    },
    {
        "keywords": ["spa", "belgium", "francorchamps"],
        "name": "Spa",
        "laps": 44,
        "length_km": 7.004,
        "record_time": "1:46.286",
        "record_driver": "VET",
        "record_year": 2018,
    },
    {
        "keywords": ["zandvoort", "netherlands", "dutch"],
        "name": "Zandvoort",
        "laps": 72,
        "length_km": 4.259,
        "record_time": "1:11.097",
        "record_driver": "VER",
        "record_year": 2021,
    },
    {
        "keywords": ["monza", "italy", "nazionale"],
        "name": "Monza",
        "laps": 53,
        "length_km": 5.793,
        "record_time": "1:21.046",
        "record_driver": "RUB",
        "record_year": 2004,
    },
    {
        "keywords": ["baku", "azerbaijan", "city circuit"],
        "name": "Baku",
        "laps": 51,
        "length_km": 6.003,
        "record_time": "1:43.009",
        "record_driver": "VER",
        "record_year": 2023,
    },
    {
        "keywords": ["singapore", "marina bay"],
        "name": "Singapore",
        "laps": 61,
        "length_km": 4.940,
        "record_time": "1:35.867",
        "record_driver": "HAM",
        "record_year": 2018,
    },
    {
        "keywords": ["americas", "cota", "austin", "texas"],
        "name": "Austin",
        "laps": 56,
        "length_km": 5.513,
        "record_time": "1:36.169",
        "record_driver": "HAM",
        "record_year": 2019,
    },
    {
        "keywords": ["rodriguez", "mexico", "hermanos"],
        "name": "Mexico City",
        "laps": 71,
        "length_km": 4.304,
        "record_time": "1:17.774",
        "record_driver": "BOT",
        "record_year": 2021,
    },
    {
        "keywords": ["interlagos", "brazil", "sao paulo"],
        "name": "São Paulo",
        "laps": 71,
        "length_km": 4.309,
        "record_time": "1:10.540",
        "record_driver": "VER",
        "record_year": 2023,
    },
    {
        "keywords": ["las vegas", "nevada", "strip"],
        "name": "Las Vegas",
        "laps": 50,
        "length_km": 6.201,
        "record_time": "1:35.490",
        "record_driver": "LEC",
        "record_year": 2023,
    },
    {
        "keywords": ["lusail", "qatar", "losail"],
        "name": "Lusail",
        "laps": 57,
        "length_km": 5.380,
        "record_time": "1:24.319",
        "record_driver": "VER",
        "record_year": 2023,
    },
    {
        "keywords": ["yas", "abu dhabi", "marina"],
        "name": "Abu Dhabi",
        "laps": 58,
        "length_km": 5.281,
        "record_time": "1:26.103",
        "record_driver": "HAM",
        "record_year": 2021,
    },
]


def get_circuit_info(circuit_name: str, city: str = "") -> Optional[Dict]:
    """Return circuit facts dict for the given circuit, or None if not found."""
    text = (circuit_name + " " + city).lower()
    for entry in _CIRCUITS:
        if any(kw in text for kw in entry["keywords"]):
            return entry
    return None
